name: CI
on:
  pull_request:
    branches:
      - master
jobs:
  build_frontend:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - run: echo ${{ github.head_ref }}
      # - name: Checkout
      #   uses: actions/checkout@v3
      #   with:
      #     ref: dev
  #     - name: Set up Nodejs
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 16
  #     - name: Install packages
  #       working-directory: Api/Client
  #       run: yarn
  #     - name: Build
  #       working-directory: Api/Client
  #       run: yarn build
  # build_backend:
  #   runs-on: ubuntu-latest
  #   environment: development
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         ref: dev
  #     - name: Set up .NET
  #       uses: actions/setup-dotnet@v2
  #       with:
  #         dotnet-version: "6.0"
  #     - name: Build
  #       run: dotnet build -c Release
